# Generated by Django 6.0.3 on 2026-03-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_beatlike_producerfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='accepts_album_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='accepts_custom_singles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='featured_beat_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='onboarding_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='service_offerings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProducerSellerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_version', models.CharField(default='v1', max_length=40)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_agreement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
