# Generated by Django 6.0.3 on 2026-03-23 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_auth_provider_user_google_sub'),
        ('beats', '0015_beat_featured_producer_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LibraryListenLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_later_entries', to='beats.beat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_later_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'beat')},
            },
        ),
        migrations.CreateModel(
            name='LibraryPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='beats.beat')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.libraryplaylist')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('playlist', 'beat')},
            },
        ),
    ]
