# Generated by Django 6.0.3 on 2026-03-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_artistprofile_avatar_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('beat_liked', 'Beat liked'), ('producer_followed', 'Producer followed'), ('project_proposal_accepted', 'Project proposal accepted')], max_length=40),
        ),
    ]
