# Generated by Django 6.0.3 on 2026-03-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoundKit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("kit_type", models.CharField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("genre", models.CharField(blank=True, max_length=80)),
                ("mood", models.CharField(blank=True, max_length=80)),
                ("bpm_min", models.PositiveIntegerField(blank=True, null=True)),
                ("bpm_max", models.PositiveIntegerField(blank=True, null=True)),
                ("base_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("cover_art_obj", models.FileField(blank=True, null=True, upload_to="soundkits/covers/")),
                ("archive_file_obj", models.FileField(blank=True, null=True, upload_to="soundkits/archives/")),
                ("preview_audio_obj", models.FileField(blank=True, null=True, upload_to="soundkits/preview/")),
                ("reference_links", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sound_kits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SoundKitUploadDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=150)),
                ("kit_type", models.CharField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("genre", models.CharField(blank=True, max_length=80)),
                ("mood", models.CharField(blank=True, max_length=80)),
                ("bpm_min", models.PositiveIntegerField(blank=True, null=True)),
                ("bpm_max", models.PositiveIntegerField(blank=True, null=True)),
                ("base_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("reference_links", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("cover_art_obj", models.FileField(blank=True, null=True, upload_to="soundkits/drafts/covers/")),
                ("archive_file_obj", models.FileField(blank=True, null=True, upload_to="soundkits/drafts/archives/")),
                ("preview_audio_obj", models.FileField(blank=True, null=True, upload_to="soundkits/drafts/preview/")),
                ("current_step", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sound_kit_upload_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_sound_kit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.soundkit",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
