# Generated by Django 6.0.3 on 2026-03-07 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beats', '0002_beat_base_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('beat', 'Beat'), ('bundle', 'Bundle'), ('tape', 'BeatTape')], max_length=20)),
                ('product_id', models.PositiveIntegerField()),
                ('product_title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('license_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beats.licensetype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_access', to='beats.beat')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_access', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_access', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='beats.beat')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_licenses', to=settings.AUTH_USER_MODEL)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.licensetype')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_license', to='orders.orderitem')),
            ],
        ),
    ]
