# Generated by Django 6.0.3 on 2026-03-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('accepted', 'Accepted')], default='submitted', max_length=30),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='version_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_timeline_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_track_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='linked_conversation_hint',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('custom_single', 'Custom Single'), ('ep', 'EP'), ('album', 'Album'), ('mix_master', 'Mix & Master'), ('sound_design', 'Sound Design')], default='custom_single', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='reference_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='revision_allowance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='target_genre_style',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_stage',
            field=models.CharField(choices=[('brief_submitted', 'Brief Submitted'), ('proposal_accepted', 'Proposal Accepted'), ('milestones_funded', 'Milestones Funded'), ('work_in_progress', 'Work In Progress'), ('deliverables_review', 'Deliverables Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='brief_submitted', max_length=30),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='delivery_timeline_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='expected_track_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='project_type',
            field=models.CharField(choices=[('custom_single', 'Custom Single'), ('ep', 'EP'), ('album', 'Album'), ('mix_master', 'Mix & Master'), ('sound_design', 'Sound Design')], default='custom_single', max_length=30),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='reference_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='revision_allowance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='target_genre_style',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('in_review', 'In Review'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
