BEAT_TYPE_VALUES = [
    "Beat",
    "Beat with Hook",
    "Switch Beat",
]

GENRE_VALUES = [
    "Acoustic",
    "Afro",
    "Afro Beat",
    "Afro Pop",
    "Alternative",
    "Alternative Hip Hop",
    "Alternative RnB",
    "Alternative Rock",
    "Ambient",
    "Ambient House",
    "Avant-Garde",
    "Baroque",
    "Beats",
    "Big Band",
    "Black Metal",
    "Bluegrass",
    "Blues",
    "Blues Rock",
    "Boom Bap",
    "Bossa Nova",
    "Breakbeat",
    "Celtic",
    "Chamber Music",
    "Chill",
    "Classical",
    "Cloud Rap",
    "Club",
    "Conscious Hip Hop",
    "Contemporary RnB",
    "Country",
    "Country Pop",
    "Country Rap",
    "Country Rock",
    "Crunk",
    "Dance",
    "Dancehall",
    "Dance Pop",
    "Death Metal",
    "Deathcore",
    "Dirty South",
    "Disco",
    "Doom Metal",
    "Downtempo",
    "Drill",
    "Drum and Bass",
    "Dub",
    "Dub Reggae",
    "Dubstep",
    "EDM",
    "East Coast",
    "Electro",
    "Electro Pop",
    "Electro Swing",
    "Electronic",
    "Emo",
    "Emo Hip Hop",
    "Experimental",
    "Experimental Hip Hop",
    "Flamenco",
    "Folk",
    "Folk Metal",
    "Folk Rock",
    "Folktronica",
    "Freestyle Rap",
    "Funk",
    "G-Funk",
    "Gangsta Rap",
    "Glam Rock",
    "Goa Trance",
    "Gospel",
    "Grime",
    "Grunge",
    "Hard Rock",
    "Hardcore Hip Hop",
    "Hip Hop",
    "Hip Hop Soul",
    "House",
    "Hyperpop",
    "Indie",
    "Indie Pop",
    "Indie Rock",
    "Industrial",
    "Industrial Metal",
    "Instrumental Hip Hop",
    "Jazz",
    "Jazz Fusion",
    "Jazz Rap",
    "Jersey Club",
    "K-Pop",
    "Latin",
    "Latin Pop",
    "Latin Trap",
    "Lo-Fi",
    "Lo-Fi Hip Hop",
    "Metal",
    "Neo Soul",
    "Nu Metal",
    "Old School Hip Hop",
    "Opera",
    "Orchestral",
    "Others",
    "Pop",
    "Pop Punk",
    "Pop Rap",
    "Pop RnB",
    "Pop Rock",
    "Post Rock",
    "Progressive Metal",
    "Psytrance",
    "Punk Rock",
    "R&B",
    "Rap Rock",
    "Reggae",
    "Reggaeton",
    "Rock",
    "Salsa",
    "Shoegaze",
    "Ska",
    "Soul",
    "Synth Pop",
    "Synthwave",
    "Techno",
    "Trance",
    "Trap",
    "Trap Metal",
    "Trip Hop",
    "Tropical House",
    "UK Garage",
    "UK Grime",
    "Underground Hip Hop",
    "West Coast",
]

INSTRUMENT_VALUES = [
    "Accordion",
    "Arpeggio",
    "Brass",
    "Choir",
    "Electric Guitar",
    "Acoustic Guitar",
    "Bass Guitar",
    "Synthesizer",
    "Flute",
    "Harp",
    "Piano",
    "Bells",
    "Saxophone",
    "Trumpet",
    "Harmonica",
    "Cello",
    "Sitar",
    "Tabla",
    "Synth Bass",
    "Strings",
    "Pads",
    "Ukulele",
    "Violin",
    "Other",
    "Alghoza",
    "Algoza",
    "Alpenhorn",
    "Alphorn",
    "Arghul",
    "Baglama",
    "Bagpipes",
    "Balalaika",
    "Banjo",
    "Bansuri",
    "Bass Drum",
    "Bassoon",
    "Been",
    "Bin",
    "Bodhran",
    "Bongo Drums",
    "Bouzouk",
    "Cajon",
    "Celesta",
    "Chapman Stick",
    "Chenda",
    "Chimta",
    "Clarinet",
    "Clavichord",
    "Conch Shell",
    "Congas",
    "Cumbus",
    "Cymbals",
    "Daf",
    "Dafli",
    "Dhadd",
    "Dhak",
    "Dhol",
    "Dholak",
    "Didgeridoo",
    "Dilruba",
    "Dizi",
    "Djembe",
    "Dotara",
    "Double Bass",
    "Drum Kit",
    "Drum Machines",
    "Duduk",
    "Eigenharp",
    "Ektara",
    "Electric Keyboard",
    "Electronic Drum Kits",
    "Erhu",
    "Esraj",
    "French Horn",
    "Gamelan Instruments",
    "Ghatam",
    "Gittern",
    "Glass Harmonica",
    "Gogona",
    "Guitar",
    "Guzheng",
    "HandSonic",
    "Hang Drum",
    "Harmonium",
    "Harpsichord",
    "Hurdy-gurdy",
    "Jal Tarang",
    "Jaltarang",
    "Jaw Harp",
    "Kalimba",
    "Kanjira",
    "Kartal",
    "Keyboard",
    "Khol",
    "Kombu",
    "Koto",
    "Laser Harp",
    "Madal",
    "Mandolin",
    "Marimba",
    "Mbira",
    "Mellotron",
    "MIDI Controllers",
    "Modular Synthesizers",
    "Mohan Veena",
    "Morsing",
    "Mridangam",
    "Naal",
    "Nadaswaram",
    "Nal Tarang",
    "Ney",
    "Oboe",
    "Ocarina",
    "Octapad",
    "Organ",
    "Pakhawaj",
    "Pan Flute",
    "Pena",
    "Pulluvan Kutam",
    "Pulluvan Veena",
    "Pungi",
    "Qanun",
    "Ravanahatha",
    "Reactable",
    "Rebab",
    "Recorder",
    "Rudra Veena",
    "Sankirtan Singing Bells",
    "Sarangi",
    "Sarod",
    "Seaboard",
    "Shakuhachi",
    "Shamisen",
    "Shehnai",
    "Shenai",
    "Sheng",
    "Snare Drum",
    "Steel Drums",
    "Synthesizer Modules",
    "Taiko Drum",
    "Taishogoto",
    "Tambourine",
    "Tanpura",
    "Tenori-on",
    "Thavil",
    "Theremin",
    "Timpani",
    "Trombone",
    "Tuba",
    "Tumbadora",
    "Tumbi",
    "Udukai",
    "Veena",
    "Vibraphone",
    "Vichitra Veena",
    "Viola",
    "Waterphone",
    "Xylophone",
    "Zither",
    "Zurna",
]

MOOD_VALUES = [
    "Aggressive",
    "Angry",
    "Bitter",
    "Bright",
    "Cheerful",
    "Cold",
    "Complex",
    "Confident",
    "Cute",
    "Dark",
    "Dramatic",
    "Elegant",
    "Energetic",
    "Epic",
    "Exotic",
    "Fun",
    "Gloomy",
    "Happy",
    "Harsh",
    "Heavy",
    "Hyper",
    "Intense",
    "Mysterious",
    "Negative",
    "Nostalgic",
    "Positive",
    "Powerful",
    "Relaxed",
    "Romantic",
    "Sad",
    "Scary",
    "Smooth",
    "Soft/Quiet",
    "Soothing",
    "Thrilling",
    "Trippy",
    "Warm",
    "Calm",
    "Cynical",
    "Accomplished",
    "Adored",
    "Annoyed",
    "Anxious",
    "Atmospheric",
    "Blissful",
    "Bouncy",
    "Brooding",
    "Captivating",
    "Chaotic",
    "Crazy",
    "Crunk",
    "Depressed",
    "Determined",
    "Dirty",
    "Disappointed",
    "Dreamy",
    "Eccentric",
    "Enigmatic",
    "Enraged",
    "Ethereal",
    "Evil",
    "Exciting",
    "Flirty",
    "Frantic",
    "Futuristic",
    "Giddy",
    "Grateful",
    "Groovy",
    "Haunting",
    "Hopeful",
    "Hypnotic",
    "Inspiring",
    "Joyful",
    "Lazy",
    "Lonely",
    "Loved",
    "Majestic",
    "Melancholic",
    "Mellow",
    "Moody",
    "Motivating",
    "Neutral",
    "Peaceful",
    "Playful",
    "Quirky",
    "Reassuring",
    "Rebellious",
    "Reflective",
    "Scared",
    "Sentimental",
    "Serene",
    "Silly",
    "Sombre",
    "Soulful",
    "Suspenseful",
    "Tense",
    "Thoughtful",
    "Triumphant",
    "Upbeat",
    "Uplifting",
    "Whimsical",
    "Wistful",
]

KEY_VALUES = [
    "C Major",
    "C# Major",
    "D Major",
    "D# Major",
    "E Major",
    "F Major",
    "F# Major",
    "G Major",
    "G# Major",
    "A Major",
    "A# Major",
    "B Major",
    "C Minor",
    "C# Minor",
    "D Minor",
    "D# Minor",
    "E Minor",
    "F Minor",
    "F# Minor",
    "G Minor",
    "G# Minor",
    "A Minor",
    "A# Minor",
    "B Minor",
    # Compatibility aliases for existing values.
    "Am",
    "Bm",
    "Cm",
    "Dm",
    "Em",
    "Fm",
    "Gm",
]

COMMERCIAL_MODE_VALUES = ["Manual", "Presets"]
PUBLISHING_RIGHTS_VALUES = [f"{value}%" for value in range(0, 101, 10)]
MASTER_RECORDING_VALUES = [f"{value} Recordings" for value in range(1, 11)]
LICENSE_PERIOD_VALUES = [f"{value} Year" if value == 1 else f"{value} Years" for value in range(1, 11)]

BEAT_TYPE_CHOICES = [(item, item) for item in BEAT_TYPE_VALUES]
GENRE_CHOICES = [(item, item) for item in GENRE_VALUES]
INSTRUMENT_CHOICES = [(item, item) for item in INSTRUMENT_VALUES]
MOOD_CHOICES = [(item, item) for item in MOOD_VALUES]
KEY_CHOICES = [(item, item) for item in KEY_VALUES]
COMMERCIAL_MODE_CHOICES = [(item, item) for item in COMMERCIAL_MODE_VALUES]
PUBLISHING_RIGHTS_CHOICES = [(item, item) for item in PUBLISHING_RIGHTS_VALUES]
MASTER_RECORDING_CHOICES = [(item, item) for item in MASTER_RECORDING_VALUES]
LICENSE_PERIOD_CHOICES = [(item, item) for item in LICENSE_PERIOD_VALUES]
