# Generated by Django 6.0.3 on 2026-03-07 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('streams_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('includes_wav', models.BooleanField(default=False)),
                ('includes_stems', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('beat_removed_on_purchase', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=80)),
                ('bpm', models.PositiveIntegerField()),
                ('key', models.CharField(blank=True, max_length=20)),
                ('mood', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('cover_art', models.URLField(blank=True)),
                ('preview_audio', models.URLField(blank=True)),
                ('audio_file', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='beats', to='beats.beattag')),
                ('available_licenses', models.ManyToManyField(blank=True, related_name='beats', to='beats.licensetype')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
