# Generated by Django 6.0.3 on 2026-03-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_beat_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='audio_file_obj',
            field=models.FileField(blank=True, null=True, upload_to='beats/audio/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='cover_art_obj',
            field=models.FileField(blank=True, null=True, upload_to='beats/covers/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='preview_audio_obj',
            field=models.FileField(blank=True, null=True, upload_to='beats/preview/'),
        ),
    ]
