# Generated by Django 6.0.3 on 2026-03-08 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_beat_audio_file_obj_beat_cover_art_obj_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatUploadDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=20)),
                ('mood', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selected_license_ids', models.JSONField(blank=True, default=list)),
                ('media', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_upload_drafts', to=settings.AUTH_USER_MODEL)),
                ('published_beat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beats.beat')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
