# Generated by Django 6.0.3 on 2026-03-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_beatuploaddraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatuploaddraft',
            name='audio_file_obj',
            field=models.FileField(blank=True, null=True, upload_to='beats/drafts/audio/'),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='cover_art_obj',
            field=models.FileField(blank=True, null=True, upload_to='beats/drafts/covers/'),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='preview_audio_obj',
            field=models.FileField(blank=True, null=True, upload_to='beats/drafts/preview/'),
        ),
    ]
