# Generated by Django 6.0.3 on 2026-03-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_alter_beat_genre_alter_beatuploaddraft_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='stems_file_obj',
            field=models.FileField(blank=True, null=True, upload_to='beats/stems/'),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='stems_file_obj',
            field=models.FileField(blank=True, null=True, upload_to='beats/drafts/stems/'),
        ),
    ]
