# Generated by Django 6.0.3 on 2026-03-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0008_beat_stems_file_obj_beatuploaddraft_stems_file_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='commercial_mode',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Presets', 'Presets')], default='Presets', max_length=20),
        ),
        migrations.AddField(
            model_name='beat',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beat',
            name='enable_free_mp3_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beat',
            name='exclusive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beat',
            name='exclusive_license_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='beat',
            name='exclusive_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beat',
            name='exclusive_publishing_rights',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=10),
        ),
        migrations.AddField(
            model_name='beat',
            name='non_exclusive_license_period',
            field=models.CharField(blank=True, choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years'), ('9 Years', '9 Years'), ('10 Years', '10 Years')], max_length=20),
        ),
        migrations.AddField(
            model_name='beat',
            name='non_exclusive_master_recordings',
            field=models.CharField(blank=True, choices=[('1 Recordings', '1 Recordings'), ('2 Recordings', '2 Recordings'), ('3 Recordings', '3 Recordings'), ('4 Recordings', '4 Recordings'), ('5 Recordings', '5 Recordings'), ('6 Recordings', '6 Recordings'), ('7 Recordings', '7 Recordings'), ('8 Recordings', '8 Recordings'), ('9 Recordings', '9 Recordings'), ('10 Recordings', '10 Recordings')], max_length=20),
        ),
        migrations.AddField(
            model_name='beat',
            name='non_exclusive_publishing_rights',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=10),
        ),
        migrations.AddField(
            model_name='beat',
            name='non_exclusive_stems_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beat',
            name='non_exclusive_stems_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='beat',
            name='non_exclusive_wav_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beat',
            name='non_exclusive_wav_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='commercial_mode',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Presets', 'Presets')], default='Presets', max_length=20),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='enable_free_mp3_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='exclusive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='exclusive_license_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='exclusive_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='exclusive_publishing_rights',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=10),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='non_exclusive_license_period',
            field=models.CharField(blank=True, choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years'), ('9 Years', '9 Years'), ('10 Years', '10 Years')], max_length=20),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='non_exclusive_master_recordings',
            field=models.CharField(blank=True, choices=[('1 Recordings', '1 Recordings'), ('2 Recordings', '2 Recordings'), ('3 Recordings', '3 Recordings'), ('4 Recordings', '4 Recordings'), ('5 Recordings', '5 Recordings'), ('6 Recordings', '6 Recordings'), ('7 Recordings', '7 Recordings'), ('8 Recordings', '8 Recordings'), ('9 Recordings', '9 Recordings'), ('10 Recordings', '10 Recordings')], max_length=20),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='non_exclusive_publishing_rights',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=10),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='non_exclusive_stems_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='non_exclusive_stems_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='non_exclusive_wav_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='non_exclusive_wav_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
