# Generated by Django 6.0.3 on 2026-03-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0009_beat_commercial_mode_beat_declaration_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='abuse_reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beat',
            name='fingerprint_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('flagged', 'Flagged')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='beat',
            name='proof_of_upload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='beat',
            name='protection_status',
            field=models.CharField(choices=[('unset', 'Unset'), ('monitored', 'Monitored'), ('protected', 'Protected')], default='unset', max_length=20),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='abuse_reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='fingerprint_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('flagged', 'Flagged')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='proof_of_upload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='beatuploaddraft',
            name='protection_status',
            field=models.CharField(choices=[('unset', 'Unset'), ('monitored', 'Monitored'), ('protected', 'Protected')], default='monitored', max_length=20),
        ),
    ]
