# Generated by Django 6.0.3 on 2026-03-23 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0015_beat_featured_producer_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatTrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=16)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.FloatField(default=0)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='beats.beat')),
            ],
            options={
                'ordering': ('period', 'rank', '-score'),
                'indexes': [models.Index(fields=['period', 'rank'], name='beats_beatt_period_9cc42d_idx'), models.Index(fields=['period', '-score'], name='beats_beatt_period_2d7c6d_idx')],
                'unique_together': {('period', 'beat')},
            },
        ),
    ]
